[mypy]
python_version = 3.9
ignore_missing_imports = False
warn_incomplete_stub = True
check_untyped_defs = True
strict_equality = True
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unused_configs = True
warn_return_any = True
warn_unreachable = True
show_error_context = True
show_column_numbers = True
show_error_codes = True
pretty = True
exclude = venv|bin|lib

[mypy-flask_cors.*]
ignore_missing_imports = True

[mypy-flasgger.*]
ignore_missing_imports = True

[mypy-mongoengine.*]
ignore_missing_imports = True

[mypy-pydash.*]
ignore_missing_imports = True

[mypy-flask_bcrypt.*]
ignore_missing_imports = True

[mypy-flask_jwt_extended.*]
ignore_missing_imports = True

[mypy-flask_restful.*]
ignore_missing_imports = True

[mypy-bson.*]
ignore_missing_imports = True

[mypy-googlemaps.*]
ignore_missing_imports = True
